### ISSUE TITLE
Cannot read property 'length' of undefined.

### ISSUE THREAD

**Issue by lewisakura** [extensionsapp/translatte#3]
Looks like Google changed how tokens work.

```js
(node:96584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at sM (E:\Node Projects\SamuelLJackson\node_modules\translatte\token.js:32:42)
    at E:\Node Projects\SamuelLJackson\node_modules\translatte\token.js:114:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:96584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:96584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lewisakura** [comment]
(nevermind, my idiocy)
